<a href="https://colab.research.google.com/github/abhishekanand04/Probability-and-Stats/blob/feature%2Fupdate/Probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment: Sachin Tendulkar ODI records for India

In [ ]:
!wget --no-check-certificate https://drive.google.com/uc?id=1zBM3idCNWceBMLKMRBTN8aVFAg5U_YH7 -O Sachin_ODI.csv

--2024-09-23 15:28:39--  https://drive.google.com/uc?id=1zBM3idCNWceBMLKMRBTN8aVFAg5U_YH7
Resolving drive.google.com (drive.google.com)... 142.251.111.113, 142.251.111.100, 142.251.111.102, ...
Connecting to drive.google.com (drive.google.com)|142.251.111.113|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1zBM3idCNWceBMLKMRBTN8aVFAg5U_YH7 [following]
--2024-09-23 15:28:40--  https://drive.usercontent.google.com/download?id=1zBM3idCNWceBMLKMRBTN8aVFAg5U_YH7
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.253.115.132, 2607:f8b0:4004:c06::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.253.115.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26440 (26K) [application/octet-stream]
Saving to: ‘Sachin_ODI.csv’

Sachin_ODI.csv      100%[===================>]  25.82K  --.-KB/s    in 0s

2024-09-23 15:28:42 (63.1 MB/s) - ‘Sachin_ODI.csv’ saved [26440/26440]

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('Sachin_ODI.csv')
df

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,14,0,34,15,2,0,93.33,2,Australia,Sydney,2012-02-26,Australia,False,False
356,39,0,45,30,5,0,130.00,2,Sri Lanka,Hobart,2012-02-28,India,True,False
357,6,0,25,19,1,0,31.57,1,Sri Lanka,Dhaka,2012-03-13,India,True,False
358,114,0,205,147,12,1,77.55,1,Bangladesh,Dhaka,2012-03-16,Bangladesh,False,True
359,52,0,93,48,5,1,108.33,2,Pakistan,Dhaka,2012-03-18,India,True,False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   runs     360 non-null    int64
 1   NotOut   360 non-null    int64
 2   mins     360 non-null    object
 3   bf       360 non-null    int64
 4   fours    360 non-null    int64
 5   sixes    360 non-null    int64
 6   sr       360 non-null    float64
 7   Inns     360 non-null    int64
 8   Opp      360 non-null    object
 9   Ground   360 non-null    object
 10  Date     360 non-null    object
 11  Winner   360 non-null    object
 12  Won      360 non-null    bool
 13  century  360 non-null    bool
dtypes: bool(2), float64(1), int64(6), object(5)
memory usage: 34.6+ KB

In [ ]:
df.shape

(360, 14)

In [ ]:
#sample space of the experiment => 360 matches

In [ ]:
#what is the probability that india have won the match played by sachin

In [ ]:
df_won = df.loc[df['Won']==True]

In [ ]:
184/360

0.5111111111111111

In [ ]:
len(df_won) #length or rows

184

In [ ]:
prob_of_winning = len(df_won)/len(df)
prob_of_winning

0.5111111111111111

In [ ]:
#prob that sachin has scored a century on that match
df['century'].value_counts()

century
False    314
True      46
Name: count, dtype: int64

In [ ]:
46/360

0.12777777777777777

In [ ]:
#if you a random match, there is 12.7% chance that sachin has scored a century in tht match

In [ ]:
#What is the probability that Sachin scores a century, given that his team has won the match?

In [ ]:
df_won = df[(df['Won']==True)]

In [ ]:
len(df_won)

184

In [ ]:
df_cent = df_won[df_won['century']==True]

In [ ]:
len(df_cent)

30

In [ ]:
#p(c|w) =
30/184

0.16304347826086957

In [ ]:
#What is the probability that Sachin's team wins AND he scores a century?

In [ ]:
df[['century','Won']].value_counts()

century  Won
False    False    160
         True     154
True     True      30
         False     16
Name: count, dtype: int64

In [ ]:
#contingency table
pd.crosstab(index = df['century'],columns=df['Won'],margins=True)

Won      False  True  All
century
False      160   154  314
True        16    30   46
All        176   184  360